artifact_location: /Users/tianqihuang/Documents/GitHub/betbot/notebooks/modeling/your_tracking_uri/265349456883963342
creation_time: 1752686355902
experiment_id: '265349456883963342'
last_update_time: 1752686355902
lifecycle_stage: active
name: your_experiment_name
